/**
 * The operation log.
 *
 * Everything the sync protocol needs lives here: what this replica knows
 * (`version`), how to enumerate what a peer is missing (`since`), and how to
 * absorb a peer's operations safely (`receive`).
 *
 * # Two guarantees the CRDT depends on
 *
 * **At most once.** Applying an operation twice would, for a multi-value
 * register, resurrect a value that a later write had already superseded. The
 * version vector plus the applied set make redelivery free — `tests/oplog`
 * feeds every operation in three times.
 *
 * **After its dependencies.** Operations that arrive early are parked in a
 * pending buffer and retried whenever something else lands, so delivery order
 * stops being a correctness concern. Without this an RGA insert could name an
 * origin that has not arrived, and there is nowhere sensible to put it.
 *
 * # Why the version vector only advances over a contiguous prefix
 *
 * `vv[replica] = 7` is a claim to hold *every* operation from that replica up
 * to 7, and `since()` relies on it to skip work. Advancing it over a gap would
 * make the replica quietly stop asking for operations it never received. So a
 * sequence number is only recorded once its predecessor has been applied;
 * anything ahead of the gap waits in the buffer.
 */

import {
  Lamport,
  OpId,
  ReplicaId,
  VersionVector,
  formatId,
  vvClone,
  vvGet,
  vvHas,
  vvSet,
} from "./clock.js";
import { Op, dependencies, opKey } from "./ops.js";

export interface ReceiveReport {
  /** Operations newly applied to the state. */
  applied: number;
  /** Already known, and skipped. */
  duplicate: number;
  /** Held back because a dependency has not arrived. */
  pending: number;
}

export class OpLog {
  /** Per-replica dense arrays indexed by `seq - 1`. */
  private byReplica = new Map<ReplicaId, Op[]>();
  private appliedKeys = new Set<string>();
  private pending = new Map<string, Op>();
  private vv: VersionVector = {};

  constructor(
    readonly lamport: Lamport,
    /** Called for each operation as it becomes causally ready. */
    private readonly onApply: (op: Op) => void,
  ) {}

  get version(): VersionVector {
    return vvClone(this.vv);
  }

  get size(): number {
    let n = 0;
    for (const ops of this.byReplica.values()) n += ops.filter(Boolean).length;
    return n;
  }

  get pendingCount(): number {
    return this.pending.size;
  }

  has(key: string): boolean {
    return this.appliedKeys.has(key);
  }

  /** Record and apply an operation generated by this replica. */
  append(op: Op): void {
    this.store(op);
    this.commit(op);
  }

  /**
   * Absorb operations from a peer.
   *
   * Sorting by Lamport timestamp first is not required for correctness — the
   * buffer would sort it out regardless — but it means the common case applies
   * in a single pass instead of degenerating into repeated retry sweeps.
   */
  receive(ops: Op[]): ReceiveReport {
    const report: ReceiveReport = { applied: 0, duplicate: 0, pending: 0 };

    const incoming = [...ops].sort((a, b) => a.id.lamport - b.id.lamport);
    for (const op of incoming) {
      const key = opKey(op);
      if (this.appliedKeys.has(key) || vvHas(this.vv, op.id)) {
        report.duplicate++;
        continue;
      }
      if (this.pending.has(key)) {
        report.duplicate++;
        continue;
      }
      this.store(op);
      this.pending.set(key, op);
    }

    report.applied = this.drain();
    report.pending = this.pending.size;
    return report;
  }

  /**
   * Apply every pending operation that has become ready, repeatedly, until a
   * full sweep changes nothing. Each application can unblock others, so a
   * single pass is not enough.
   */
  private drain(): number {
    let total = 0;
    for (;;) {
      let progress = 0;
      for (const [key, op] of [...this.pending]) {
        if (!this.ready(op)) continue;
        this.pending.delete(key);
        this.commit(op);
        progress++;
      }
      total += progress;
      if (progress === 0) return total;
    }
  }

  private ready(op: Op): boolean {
    // The contiguity rule that keeps the version vector honest.
    if (op.id.seq !== vvGet(this.vv, op.id.replica) + 1) return false;
    for (const dep of dependencies(op)) {
      if (!this.appliedKeys.has(dep)) return false;
    }
    return true;
  }

  private commit(op: Op): void {
    this.lamport.observe(op.id.lamport);
    this.appliedKeys.add(opKey(op));
    vvSet(this.vv, op.id.replica, op.id.seq);
    this.onApply(op);
  }

  private store(op: Op): void {
    let ops = this.byReplica.get(op.id.replica);
    if (!ops) {
      ops = [];
      this.byReplica.set(op.id.replica, ops);
    }
    ops[op.id.seq - 1] = op;
  }

  /**
   * Operations a peer holding `theirs` does not have.
   *
   * Cost is proportional to the number of *missing* operations, not to the log
   * size, because the dense per-replica arrays let this start at the peer's
   * high-water mark. This is the property that makes syncing a one-character
   * edit cost one operation on a log with a million of them, and
   * `tests/sync.test.ts` asserts it rather than assuming it.
   */
  since(theirs: VersionVector): Op[] {
    const out: Op[] = [];
    for (const [replica, ops] of this.byReplica) {
      const from = vvGet(theirs, replica);
      for (let i = from; i < ops.length; i++) {
        const op = ops[i];
        if (op) out.push(op);
      }
    }
    return out.sort((a, b) => a.id.lamport - b.id.lamport);
  }

  /** Every operation, oldest first. Used to rebuild state from storage. */
  all(): Op[] {
    const out: Op[] = [];
    for (const ops of this.byReplica.values()) for (const op of ops) if (op) out.push(op);
    return out.sort((a, b) => a.id.lamport - b.id.lamport);
  }

  /** Next sequence number for this replica. */
  nextSeq(replica: ReplicaId): number {
    return vvGet(this.vv, replica) + 1;
  }

  mint(replica: ReplicaId): OpId {
    return { replica, seq: this.nextSeq(replica), lamport: this.lamport.tick() };
  }

  /** Keys of operations stuck waiting on dependencies, for diagnostics. */
  pendingKeys(): string[] {
    return [...this.pending.keys()];
  }

  /** Dependencies that pending operations are waiting for. */
  missingDependencies(): string[] {
    const missing = new Set<string>();
    for (const op of this.pending.values()) {
      for (const dep of dependencies(op)) {
        if (!this.appliedKeys.has(dep)) missing.add(dep);
      }
      const expected = vvGet(this.vv, op.id.replica) + 1;
      if (op.id.seq !== expected) missing.add(formatId({ ...op.id, seq: expected }));
    }
    return [...missing];
  }
}
